### PR TITLE
Add @inlinable/@usableFromInline attributes to public/internal declar…

### PR DESCRIPTION
**Pull request by lukaszklekot**
…ations

### CODE REVIEW

**Comment by lukaszklekot** [comment]
Huh, looks like travis uses a Swift version < 4.2.

**Comment by stephencelis** [comment]
@lukaszklekot Ah, we should fix that :) Thanks for the PR! We added `@inlinable` and `@usableFromInline` all over [Gen](https://github.com/pointfreeco/swift-gen) and found it made the performance a lot better. Have you benchmarked the impact here? I have to admit I'm still wrapping my head around when it's appropriate to use `@inlinable` vs. when it's _not_ appropriate. Do you have any thoughts here?

**Comment by lukaszklekot** [comment]
@stephencelis No, unfortunately I have not benchmarked anything (but probably should 😳).
As stated in the evolution proposal, I would annotate all public APIs that are fairly simple but make use of generics to give the compiler a chance to optimise them. But you are right, benchmarks would give us a better overview of when we should do this.

**Comment by lukaszklekot** [comment]
@stephencelis I made a couple of measurements with XCTest. The performance gain (90-100%) makes me a little suspicious.
What I'm doing is something like this:
```swift
  func testMeasureChain() {
    let testCount = 1_000_000
    var a: [Int?] = Array(repeating: nil, count: testCount)
    measure {
      for n in 0 ..< testCount {
//        a[n] = chain(incr, addN(n))(2)
        a[n] = chain_inlinable(incr, addN(n))(2)
      }
    }
  }
```
Do you have any thoughts on how to write a meaningful benchmark?

**Pull request closed without merging**
