### PR TITLE
Added Uncurry 🍛

### PR DESCRIPTION
**Pull request by RuiAAPeres**
As the title says. 

I tried to keep the styling consistent with what we have in curry, but happy to change for something else.

### CODE REVIEW

**Comment by stephencelis** [comment]
Thanks! Looks like the swiftenv install script URL is broken, causing the CI failure. Gonna try to fix and then merge mast into this branch.

**Comment by stephencelis** [comment]
Can you merge master into this branch and see if that fixes CI?

**Comment by RuiAAPeres** [comment]
Done. 🚀

**Comment by stephencelis** [comment]
Beautiful, thanks!

**Pull request merged**
